# Application for FPT 1st job

InternApplication(1_Application):
    job: fptFirstJob
    resume: dungNguyenFirstResume
    postedAt: 2012-04-21
    jobSeeker: dungnguyen
    employer: fpt
    message: I would like to apply for this job

InternApplication(2_Application):
    job: fptFirstJob
    resume: vanndFirstResume
    postedAt: 2012-04-19
    jobSeeker: vannd
    employer: fpt
    message: I would like to apply for this job

InternApplication(3_Application):
    job: fptFirstJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-14
    jobSeeker: nguyenquac
    employer: fpt
    message: I would like to apply for this job

InternApplication(4_Application):
    job: fptFirstJob
    resume: trieultFirstResume
    postedAt: 2012-04-15
    jobSeeker: trieult
    employer: fpt
    message: I would like to apply for this job

InternApplication(5_Application):
    job: fptFirstJob
    resume: hoangtnFirstResume
    postedAt: 2012-04-21
    jobSeeker: hoangtn
    employer: fpt
    message: I would like to apply for this job

InternApplication(6_Application):
    job: fptFirstJob
    resume: kienbdFirstResume
    postedAt: 2012-04-18
    jobSeeker: kienbd
    employer: fpt
    message: I would like to apply for this job

InternApplication(7_Application):
    job: fptFirstJob
    resume: ductmFirstResume
    postedAt: 2012-04-21
    jobSeeker: ductm
    employer: fpt
    message: I would like to apply for this job

InternApplication(8_Application):
    job: fptFirstJob
    resume: tungddFirstResume
    postedAt: 2012-04-21
    jobSeeker: tungdd
    employer: fpt
    message: I would like to apply for this job

# Application for FPT 2nd job

InternApplication(9_Application):
    job: fptSecondJob
    resume: dungNguyenFirstResume
    postedAt: 2012-04-16
    jobSeeker: dungnguyen
    employer: fpt
    message: I would like to apply for this job

InternApplication(10_Application):
    job: fptSecondJob
    resume: vanndFirstResume
    postedAt: 2012-04-17
    jobSeeker: vannd
    employer: fpt
    message: I would like to apply for this job

InternApplication(11_Application):
    job: fptSecondJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-16
    jobSeeker: nguyenquac
    employer: fpt
    message: I would like to apply for this job

InternApplication(12_Application):
    job: fptSecondJob
    resume: thanhncFirstResume
    postedAt: 2012-04-16
    jobSeeker: thanhnc
    employer: fpt
    message: I would like to apply for this job

InternApplication(13_Application):
    job: fptSecondJob
    resume: quanntFirstResume
    postedAt: 2012-04-16
    jobSeeker: quannt
    employer: fpt
    message: I would like to apply for this job

InternApplication(14_Application):
    job: fptSecondJob
    resume: quanleFirstResume
    postedAt: 2012-04-17
    jobSeeker: quanle
    employer: fpt
    message: I would like to apply for this job

# Application for FPT 3rd job

InternApplication(15_Application):
    job: fptThirdJob
    resume: tudoanFirstResume
    postedAt: 2012-04-17
    jobSeeker: tudoan
    employer: fpt
    message: I would like to apply for this job

InternApplication(16_Application):
    job: fptThirdJob
    resume: ductmFirstResume
    postedAt: 2012-04-18
    jobSeeker: ductm
    employer: fpt
    message: I would like to apply for this job

InternApplication(17_Application):
    job: fptThirdJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-18
    jobSeeker: nguyenquac
    employer: fpt
    message: I would like to apply for this job

InternApplication(18_Application):
    job: fptThirdJob
    resume: tungddFirstResume
    postedAt: 2012-04-19
    jobSeeker: tungdd
    employer: fpt
    message: I would like to apply for this job

# Application for Sunnet 1st job

InternApplication(19_Application):
    job: sunnetFirstJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-18
    jobSeeker: nguyenquac
    employer: sunnet
    message: I would like to apply for this job

InternApplication(20_Application):
    job: sunnetFirstJob
    resume: vanndFirstResume
    postedAt: 2012-04-19
    jobSeeker: vannd
    employer: sunnet
    message: I would like to apply for this job

InternApplication(21_Application):
    job: sunnetFirstJob
    resume: dungnguyenFirstResume
    postedAt: 2012-04-18
    jobSeeker: dungnguyen
    employer: sunnet
    message: I would like to apply for this job

InternApplication(22_Application):
    job: sunnetFirstJob
    resume: thanhncFirstResume
    postedAt: 2012-04-18
    jobSeeker: thanhnc
    employer: sunnet
    message: I would like to apply for this job

InternApplication(23_Application):
    job: sunnetFirstJob
    resume: tungddFirstResume
    postedAt: 2012-04-18
    jobSeeker: tungdd
    employer: sunnet
    message: I would like to apply for this job

# Application for Sunnet 2nd job

InternApplication(24_Application):
    job: sunnetSecondJob
    resume: ductmFirstResume
    postedAt: 2012-04-18
    jobSeeker: ductm
    employer: sunnet
    message: I would like to apply for this job

InternApplication(25_Application):
    job: sunnetSecondJob
    resume: trieultFirstResume
    postedAt: 2012-04-18
    jobSeeker: trieult
    employer: sunnet
    message: I would like to apply for this job

InternApplication(26_Application):
    job: sunnetSecondJob
    resume: thanhncFirstResume
    postedAt: 2012-04-20
    jobSeeker: thanhnc
    employer: sunnet
    message: I would like to apply for this job

InternApplication(27_Application):
    job: sunnetSecondJob
    resume: hoangtnFirstResume
    postedAt: 2012-04-20
    jobSeeker: hoangtn
    employer: sunnet
    message: I would like to apply for this job

InternApplication(28_Application):
    job: sunnetSecondJob
    resume: quanleFirstResume
    postedAt: 2012-04-20
    jobSeeker: quanle
    employer: sunnet
    message: I would like to apply for this job

# Application for Sunnet 3rd job

InternApplication(29_Application):
    job: sunnetThirdJob
    resume: ductmFirstResume
    postedAt: 2012-04-18
    jobSeeker: ductm
    employer: sunnet
    message: I would like to apply for this job

InternApplication(30_Application):
    job: sunnetThirdJob
    resume: trieultFirstResume
    postedAt: 2012-04-18
    jobSeeker: trieult
    employer: sunnet
    message: I would like to apply for this job

InternApplication(31_Application):
    job: sunnetThirdJob
    resume: thanhncFirstResume
    postedAt: 2012-04-20
    jobSeeker: thanhnc
    employer: sunnet
    message: I would like to apply for this job

InternApplication(32_Application):
    job: sunnetThirdJob
    resume: hoangtnFirstResume
    postedAt: 2012-04-20
    jobSeeker: hoangtn
    employer: sunnet
    message: I would like to apply for this job

InternApplication(33_Application):
    job: sunnetThirdJob
    resume: quanleFirstResume
    postedAt: 2012-04-20
    jobSeeker: quanle
    employer: sunnet
    message: I would like to apply for this job

# Application for VTC 1st job

InternApplication(34_Application):
    job: vtcmobileFirstJob
    resume: dungNguyenFirstResume
    postedAt: 2012-04-21
    jobSeeker: dungnguyen
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(35_Application):
    job: vtcmobileFirstJob
    resume: vanndFirstResume
    postedAt: 2012-04-19
    jobSeeker: vannd
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(36_Application):
    job: vtcmobileFirstJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-14
    jobSeeker: nguyenquac
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(37_Application):
    job: vtcmobileFirstJob
    resume: trieultFirstResume
    postedAt: 2012-04-15
    jobSeeker: trieult
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(38_Application):
    job: vtcmobileFirstJob
    resume: hoangtnFirstResume
    postedAt: 2012-04-21
    jobSeeker: hoangtn
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(39_Application):
    job: vtcmobileFirstJob
    resume: kienbdFirstResume
    postedAt: 2012-04-18
    jobSeeker: kienbd
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(40_Application):
    job: vtcmobileFirstJob
    resume: ductmFirstResume
    postedAt: 2012-04-21
    jobSeeker: ductm
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(41_Application):
    job: vtcmobileFirstJob
    resume: tungddFirstResume
    postedAt: 2012-04-21
    jobSeeker: tungdd
    employer: vtcmobile
    message: I would like to apply for this job

# Application for vtcmobile 2nd job

InternApplication(42_Application):
    job: vtcmobileSecondJob
    resume: dungNguyenFirstResume
    postedAt: 2012-04-16
    jobSeeker: dungnguyen
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(43_Application):
    job: vtcmobileSecondJob
    resume: vanndFirstResume
    postedAt: 2012-04-17
    jobSeeker: vannd
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(44_Application):
    job: vtcmobileSecondJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-16
    jobSeeker: nguyenquac
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(45_Application):
    job: vtcmobileSecondJob
    resume: thanhncFirstResume
    postedAt: 2012-04-16
    jobSeeker: thanhnc
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(46_Application):
    job: vtcmobileSecondJob
    resume: quanntFirstResume
    postedAt: 2012-04-16
    jobSeeker: quannt
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(47_Application):
    job: vtcmobileSecondJob
    resume: quanleFirstResume
    postedAt: 2012-04-17
    jobSeeker: quanle
    employer: vtcmobile
    message: I would like to apply for this job

# Application for vtcmobile 3rd job

InternApplication(48_Application):
    job: vtcmobileThirdJob
    resume: tudoanFirstResume
    postedAt: 2012-04-17
    jobSeeker: tudoan
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(49_Application):
    job: vtcmobileThirdJob
    resume: ductmFirstResume
    postedAt: 2012-04-18
    jobSeeker: ductm
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(50_Application):
    job: vtcmobileThirdJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-18
    jobSeeker: nguyenquac
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(51_Application):
    job: vtcmobileThirdJob
    resume: tungddFirstResume
    postedAt: 2012-04-19
    jobSeeker: tungdd
    employer: vtcmobile
    message: I would like to apply for this job

# Application for vtcmobile 4th job

InternApplication(52_Application):
    job: vtcmobileFourthJob
    resume: tudoanFirstResume
    postedAt: 2012-04-17
    jobSeeker: tudoan
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(53_Application):
    job: vtcmobileFourthJob
    resume: ductmFirstResume
    postedAt: 2012-04-18
    jobSeeker: ductm
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(54_Application):
    job: vtcmobileFourthJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-18
    jobSeeker: nguyenquac
    employer: vtcmobile
    message: I would like to apply for this job

InternApplication(55_Application):
    job: vtcmobileFourthJob
    resume: tungddFirstResume
    postedAt: 2012-04-19
    jobSeeker: tungdd
    employer: vtcmobile
    message: I would like to apply for this job

# Application for MISA 1st job

InternApplication(56_Application):
    job: misaFirstJob
    resume: dungNguyenFirstResume
    postedAt: 2012-04-21
    jobSeeker: dungnguyen
    employer: misa
    message: I would like to apply for this job

InternApplication(57_Application):
    job: misaFirstJob
    resume: vanndFirstResume
    postedAt: 2012-04-19
    jobSeeker: vannd
    employer: misa
    message: I would like to apply for this job

InternApplication(58_Application):
    job: misaFirstJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-14
    jobSeeker: nguyenquac
    employer: misa
    message: I would like to apply for this job

InternApplication(59_Application):
    job: misaFirstJob
    resume: trieultFirstResume
    postedAt: 2012-04-15
    jobSeeker: trieult
    employer: misa
    message: I would like to apply for this job

InternApplication(60_Application):
    job: misaFirstJob
    resume: hoangtnFirstResume
    postedAt: 2012-04-21
    jobSeeker: hoangtn
    employer: misa
    message: I would like to apply for this job

InternApplication(61_Application):
    job: misaFirstJob
    resume: kienbdFirstResume
    postedAt: 2012-04-18
    jobSeeker: kienbd
    employer: misa
    message: I would like to apply for this job

InternApplication(62_Application):
    job: misaFirstJob
    resume: ductmFirstResume
    postedAt: 2012-04-21
    jobSeeker: ductm
    employer: misa
    message: I would like to apply for this job

InternApplication(63_Application):
    job: misaFirstJob
    resume: tungddFirstResume
    postedAt: 2012-04-21
    jobSeeker: tungdd
    employer: misa
    message: I would like to apply for this job

# Application for misa 2nd job

InternApplication(64_Application):
    job: misaSecondJob
    resume: dungNguyenFirstResume
    postedAt: 2012-04-16
    jobSeeker: dungnguyen
    employer: misa
    message: I would like to apply for this job

InternApplication(65_Application):
    job: misaSecondJob
    resume: vanndFirstResume
    postedAt: 2012-04-17
    jobSeeker: vannd
    employer: misa
    message: I would like to apply for this job

InternApplication(66_Application):
    job: misaSecondJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-16
    jobSeeker: nguyenquac
    employer: misa
    message: I would like to apply for this job

InternApplication(67_Application):
    job: misaSecondJob
    resume: thanhncFirstResume
    postedAt: 2012-04-16
    jobSeeker: thanhnc
    employer: misa
    message: I would like to apply for this job

InternApplication(68_Application):
    job: misaSecondJob
    resume: quanntFirstResume
    postedAt: 2012-04-16
    jobSeeker: quannt
    employer: misa
    message: I would like to apply for this job

InternApplication(69_Application):
    job: misaSecondJob
    resume: quanleFirstResume
    postedAt: 2012-04-17
    jobSeeker: quanle
    employer: misa
    message: I would like to apply for this job

# Application for misa 3rd job

InternApplication(70_Application):
    job: misaThirdJob
    resume: tudoanFirstResume
    postedAt: 2012-04-17
    jobSeeker: tudoan
    employer: misa
    message: I would like to apply for this job

InternApplication(71_Application):
    job: misaThirdJob
    resume: ductmFirstResume
    postedAt: 2012-04-18
    jobSeeker: ductm
    employer: misa
    message: I would like to apply for this job

InternApplication(72_Application):
    job: misaThirdJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-18
    jobSeeker: nguyenquac
    employer: misa
    message: I would like to apply for this job

InternApplication(73_Application):
    job: misaThirdJob
    resume: tungddFirstResume
    postedAt: 2012-04-19
    jobSeeker: tungdd
    employer: misa
    message: I would like to apply for this job

# Application for misa 4th job

InternApplication(74_Application):
    job: misaFourthJob
    resume: tudoanFirstResume
    postedAt: 2012-04-17
    jobSeeker: tudoan
    employer: misa
    message: I would like to apply for this job

InternApplication(75_Application):
    job: misaFourthJob
    resume: ductmFirstResume
    postedAt: 2012-04-18
    jobSeeker: ductm
    employer: misa
    message: I would like to apply for this job

InternApplication(76_Application):
    job: misaFourthJob
    resume: nguyenquacFirstResume
    postedAt: 2012-04-18
    jobSeeker: nguyenquac
    employer: misa
    message: I would like to apply for this job

InternApplication(77_Application):
    job: misaFourthJob
    resume: tungddFirstResume
    postedAt: 2012-04-19
    jobSeeker: tungdd
    employer: misa
    message: I would like to apply for this job